---
name: ProtonMail bridge
version: 1.4.1
slug: pmb
description: Send emails using your ProtonMail account
url: https://github.com/themerovingien/home_assitant_rrepo/tree/main/ha-protonmail-bridge
boot: auto
startup: system
arch: 
    - armhf
    - armv7
    - aarch64
    - amd64
image: themerovingien/ha-protonmail-bridge-{arch}
auth_api: true
ports:
    25/tcp: 25
    143/tcp: 143
ports_description:
    25/tcp: SMTP port. 25 is the default for SMTP servers.
    143/tcp: IMAP port. 143 is the default for IMAP servers. 
options: 
    username: null
    password: null
    two_factor_code: ""
schema: 
    username: str
    password: password
    two_factor_code: str?
